Repository kubeshop/testkube, pull requests merged in 2021-09, with the labels that each got.

#277 Script duration fix + ports fix
  Makefile
  api/v1/kubtest.yaml
  build/api-server/Dockerfile
  cmd/api-server/main.go
  docs/installing.md
  pkg/api/client/direct.go
  pkg/api/client/proxy.go
  pkg/api/client/proxy_test.go
  pkg/ui/errors.go
  pkg/worker/worker.go
  test/e2e/e2e_test.go
Labels: service:api 🎡

#296 added postman collection e2e test for API server
  Makefile
  api/v1/kubtest.yaml
  data.json
  internal/app/api/v1/scripts.go
  pkg/api/kubtest/model_execution_summary.go
  test/e2e/Kubtest-Sanity.postman_collection.json
  test/e2e/local-postman.yaml
Labels: 🧪 tests

#303 updated kubtest-operator with additional fields
  go.mod
  go.sum
Labels: service:operator 🎡, service:api 🎡

#326 executions summary fix
  cmd/kubectl-kubtest/commands/scripts/listrenderer.go
  pkg/api/v1/client/direct.go
  pkg/api/v1/client/interface.go
  pkg/api/v1/client/proxy.go
  pkg/api/v1/kubtest/model_execution_summary_extended.go
  test/e2e/Health.postman_collection.json
  test/e2e/LocalHealth.postman_collection.json
Labels: bug 🐛

#325 feat: Add option to install/uninstall ingress.
  cmd/kubectl-kubtest/commands/constants.go
  cmd/kubectl-kubtest/commands/install.go
  cmd/kubectl-kubtest/commands/uninstall.go
  docs/installing.md
  pkg/jobs/jobclient.go
  pkg/k8sclient/k8sclient.go
  pkg/ui/errors.go
Labels: enhancement
