Repository kubeshop/testkube, pull requests merged in 2022-01, with the labels that each got.

#683 refactor: use agregate to get execution totals from mongo db
  internal/pkg/api/repository/result/mongo.go
Labels: enhancement

#691 feat(tags): add tags endpoint
  api/v1/testkube.yaml
  internal/app/api/v1/executions.go
  internal/app/api/v1/server.go
  internal/app/api/v1/tags.go
  internal/app/api/v1/tests.go
  internal/pkg/api/repository/result/interface.go
  internal/pkg/api/repository/result/mongo.go
  internal/pkg/api/repository/result/mongo_test.go
Labels: enhancement

#693 fix(tags): slice access out of range
  internal/pkg/api/repository/result/mongo.go
  internal/pkg/api/repository/result/mongo_test.go
Labels: bug 🐛

#761 fix: improve list all tags handler
  go.mod
  go.sum
  internal/app/api/v1/tags.go
  internal/app/api/v1/tests.go
  pkg/utils/utils.go
Labels: enhancement

#782 fix: don't use dash for get all executions
  cmd/kubectl-testkube/commands/scripts.go
  cmd/kubectl-testkube/commands/scripts/common.go
  cmd/kubectl-testkube/commands/scripts/executions.go
  cmd/kubectl-testkube/commands/scripts/get_script_execution.go
  cmd/kubectl-testkube/commands/scripts/start.go
  cmd/kubectl-testkube/commands/scripts/watch.go
  internal/app/api/v1/executions.go
  internal/app/api/v1/server.go
  internal/app/api/v1/tests.go
  pkg/api/v1/client/direct.go
  pkg/api/v1/client/direct_test.go
  pkg/api/v1/client/interface.go
  pkg/api/v1/client/proxy.go
Labels: enhancement

#855 docs: add general README improvements
  README.md
Labels: 🧾 documentation
