Repository kubeshop/testkube, pull requests merged in 2022-07, with the labels that each got.

#1660 feat: add execution number to executions
  cmd/kubectl-testkube/commands/tests/common.go
  cmd/kubectl-testkube/commands/tests/renderer/execution_obj.go
  internal/app/api/v1/executions.go
  pkg/api/v1/testkube/model_execution.go
  pkg/api/v1/testkube/model_execution_extended.go
  pkg/api/v1/testkube/model_execution_request.go
  pkg/api/v1/testkube/model_execution_summary.go
  pkg/mapper/executions/sumary_test.go
  pkg/mapper/executions/summary.go
Labels: enhancement

#1818 fix: segmentation fault on getting execution labels
  pkg/api/v1/testkube/model_test_suite_with_execution_base_extended.go
  pkg/api/v1/testkube/model_test_with_execution_base_extended.go
Labels: bug 🐛

#1826 feat: merge test name and execution number into execution name
  cmd/kubectl-testkube/commands/tests/common.go
  cmd/kubectl-testkube/commands/tests/renderer/execution_obj.go
  internal/app/api/v1/executions.go
  internal/app/api/v1/testsuites.go
  pkg/api/v1/testkube/model_execution_extended.go
  pkg/api/v1/testkube/model_executions_result_extended.go
Labels: enhancement

#1832 docs: Update Readme with more executors
  README.md
Labels: 🧾 documentation
